project_id = "elebtxleydldblwcidmq"

[functions.send-tax-reminder]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.send-rent-reminder]
verify_jwt = false

[functions.generate-invoices]
verify_jwt = false

[functions.generate-receipt]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false
